<?php
add_action( 'init', function () {
register_post_type( 'crb_service', array(
	'labels' => array(
		'name' => __( 'Programs', 'sage' ),
		'singular_name' => __( 'Program', 'sage' ),
		'add_new' => __( 'Add New', 'sage' ),
		'add_new_item' => __( 'Add new Program', 'sage' ),
		'view_item' => __( 'View Program', 'sage' ),
		'edit_item' => __( 'Edit Program', 'sage' ),
		'new_item' => __( 'New Program', 'sage' ),
		'view_item' => __( 'View Program', 'sage' ),
		'search_items' => __( 'Search Programs', 'sage' ),
		'not_found' =>  __( 'No Programs found', 'sage' ),
		'not_found_in_trash' => __( 'No Programs found in trash', 'sage' ),
	),
	'public' => true,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' => 'post.php?post=%d',
	'rewrite' => array(
		'slug' => 'program',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-awards',
	'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
) );

register_post_type( 'crb_testimonial', array(
	'labels' => array(
		'name' => __( 'Testimonials', 'sage' ),
		'singular_name' => __( 'Testimonial', 'sage' ),
		'add_new' => __( 'Add New', 'sage' ),
		'add_new_item' => __( 'Add new Testimonial', 'sage' ),
		'view_item' => __( 'View Testimonial', 'sage' ),
		'edit_item' => __( 'Edit Testimonial', 'sage' ),
		'new_item' => __( 'New Testimonial', 'sage' ),
		'view_item' => __( 'View Testimonial', 'sage' ),
		'search_items' => __( 'Search Testimonials', 'sage' ),
		'not_found' =>  __( 'No Testimonials found', 'sage' ),
		'not_found_in_trash' => __( 'No Testimonials found in trash', 'sage' ),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' => 'post.php?post=%d',
	'rewrite' => array(
		'slug' => 'testimonial',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-heart',
	'supports' => array( 'title', 'editor' ),
) );

register_post_type( 'crb_member', array(
	'labels' => array(
		'name' => __( 'Team Members', 'sage' ),
		'singular_name' => __( 'Team Member', 'sage' ),
		'add_new' => __( 'Add New', 'sage' ),
		'add_new_item' => __( 'Add new Team Member', 'sage' ),
		'view_item' => __( 'View Team Member', 'sage' ),
		'edit_item' => __( 'Edit Team Member', 'sage' ),
		'new_item' => __( 'New Team Member', 'sage' ),
		'view_item' => __( 'View Team Member', 'sage' ),
		'search_items' => __( 'Search Team Members', 'sage' ),
		'not_found' =>  __( 'No Team Members found', 'sage' ),
		'not_found_in_trash' => __( 'No Team Members found in trash', 'sage' ),
	),
	'public' => true,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' => 'post.php?post=%d',
	'rewrite' => array(
		'slug' => 'about',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-groups',
	'supports' => array( 'title', 'thumbnail' ),
) );

register_post_type( 'crb_tour', array(
	'labels' => array(
		'name' => __( '360° Gallery', 'sage' ),
		'singular_name' => __( '360° Gallery', 'sage' ),
		'add_new' => __( 'Add New Image', 'sage' ),
		'add_new_item' => __( 'Add new Image', 'sage' ),
		'view_item' => __( 'View Image', 'sage' ),
		'edit_item' => __( 'Edit Image', 'sage' ),
		'new_item' => __( 'New Image', 'sage' ),
		'view_item' => __( 'View Image', 'sage' ),
		'search_items' => __( 'Search Images', 'sage' ),
		'not_found' =>  __( 'No Images found', 'sage' ),
		'not_found_in_trash' => __( 'No Images found in trash', 'sage' ),
	),
	'public' => false,
	'exclude_from_search' => true,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => false,
	'_edit_link' => 'post.php?post=%d',
	'rewrite' => array(
		'slug' => 'tour',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-format-gallery',
	'supports' => array( 'title' ),
) );

register_post_type( 'crb_news', array(
	'labels' => array(
		'name' => __( 'News', 'sage' ),
		'singular_name' => __( 'News', 'sage' ),
		'add_new' => __( 'Add New', 'sage' ),
		'add_new_item' => __( 'Add new News', 'sage' ),
		'view_item' => __( 'View News', 'sage' ),
		'edit_item' => __( 'Edit News', 'sage' ),
		'new_item' => __( 'New New', 'sage' ),
		'view_item' => __( 'View News', 'sage' ),
		'search_items' => __( 'Search News', 'sage' ),
		'not_found' =>  __( 'No News found', 'sage' ),
		'not_found_in_trash' => __( 'No News found in trash', 'sage' ),
	),
	'public' => true,
	'has_archive' => true,
	'exclude_from_search' => false,
	'show_ui' => true,
	'capability_type' => 'post',
	'hierarchical' => true,
	'_edit_link' => 'post.php?post=%d',
	'rewrite' => array(
		'slug' => 'news',
		'with_front' => false,
	),
	'query_var' => true,
	'menu_icon' => 'dashicons-admin-site',
	'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt' ),
) );
register_taxonomy("news-categories", array("crb_news"), array("hierarchical" => true, "label" => "Categories", "singular_label" => "Category", "rewrite" => array( 'slug' => 'news-categories', 'with_front'=> false )));
} );